### ISSUE TITLE
Tests not working properly

### ISSUE THREAD

**Issue by ramirezfranciscof** [nanolebrero/lio#48] opened 2015-07-13 20:23 UTC
This is just me or happens to everyone? Issues I have noticed:

(1) After make clean in the main folder, the tests won't work, apparently because some things are not compiled (liosolo as far as I could tell). Compiling before running the tests allows 0_aguaCPU and 0_aguaGPU run correctly. This should not be necessary, the tests should compile liosolo if needed by themselves.

(2) Some test cases won't even run correctly after that. I still haven't tried all of them, but I get at least the following errors:

```
Running 10_fullerenoCPU...
    Recompiling...
    Options: cpu=1 openmp=0 time=1
    Recompiling Done
    Running...
./correr.sh: line 11:  1370 Segmentation fault      (core dumped) $LIOBIN -i fullereno.in -b DZVP -c fullereno.xyz -v > $SALIDA
    Failed to run with errcode 139


Running 10_fullerenoGPU...
    Recompiling...
    Options: cuda=1 sm20=1 time=1
    Recompiling Done
    Running...
./correr.sh: line 11:  2275 Segmentation fault      (core dumped) $LIOBIN -i fullereno.in -b DZVP -c fullereno.xyz -v > $SALIDA
    Failed to run with errcode 139


Running 11_fosfato_QMMM...
    Recompiling...
    Options: cuda=1 sm20=1 time=1
    Recompiling Done
    Running...
    Failed because no ideal output in directory

Running 1_Oxy-molGPU...
Recompiling...
Options: cuda=1 sm20=1 time=1
Recompiling Done
Running...
terminate called after throwing an instance of 'std::runtime_error'
what():  El ancho no puede ser 0
./correr.sh: line 11:  4463 Aborted                 (core dumped) $LIOBIN -i Oxy-mol.in -b DZVP -c Oxy-mol.xyz -v > $SALIDA
Failed to run with errcode 134
```

This may be due simply to a change in input keyword or make options; I am still trying to decipher how the python scripts work (not familiar with the language), which is something I am interested in understanding, so I just wanted to check if this was happening to all of you and if any of you knows the logic of the scripts.

Also, I take the opportunity to suggest that we rethink the way we have organized the testing. I will be researching a little further on the subject, but I think our current tests are not ideal.

**Comment by chopkins906** [comment] 2015-07-13 21:39
(1) Yep, it looks like the python test suite is just for testing g2g and expects lioamber and liosolo to have already been compiled.

I would agree that the current setup with the python script isn't ideal - considering this fact it only does g2g, and the way it always seems to recompile for each test - it would be nice to be able to compile one version first (e.g. GPU or CPU version) and then just run the tests appropriate to that type of build without recompilation - unless I'm missing the way to do that?

(2) There seems to be a particular problem with each of those tests:

- fullereno test I get this error:
DIMENSION PROBLEMS WITH AUXILIAR BASIS PARAMETER NGD
It appears the basis set size for that test is larger than the default parameters set up in either garcha_mod.f or param.f - currently the only way to change those is to manually edit the file and recompile, so I'm not sure the best way to fix this test (either 1)the basis set parameters need to be made modifiable via a compile flag, 2)the user has to be assumed to have set the parameters correctly before running the test, 3)take out that test, or 4) make the default parameters in param.f larger)

-fosfato_QMMM seems to have a bad path in correr.sh; it's a simple fix, I can push a fix for it

-Oxy-molGPU is an OpenShell test, I think, and as @williamagudelo82 mentioned elsewhere, OpenShell is not supported yet with the new OpenMP GPU code in rc, so I guess that test needs to be taken out for now?

-I'll also mention that the CPU tests aren't compiling correctly, I believe ,due to missing the cuda=0 flag, I'll push a fix for that too

**Comment by chopkins906** [comment] 2015-07-13 21:56
Actually, it seems that the QMMM test was also missing a "salida.ok" file, if I copy salida.580.ok to salida.ok, then it completes.  However, for me the test is failing with:

SCF Diff: 0.001315

which is about a 0.8 kcal/mol difference I think... I tried with the CPU QM/MM code and got the same answer, so I'm not sure what the problem is...

**Comment by ramirezfranciscof** [comment] 2015-07-14 19:58
(1) Since I would think that compiling flags should not affect program functionality (disregarding the current situation where OpenShell is not supported in GPU as an "in development" situation), I then also consider that having separated tests by compilation options (GPU, CPU) is not necessary. That can be changed directly from the running script, so it compiles once for each option combination, and then tries all tests with that. Am I missing something here?

We've been talking with @nanolebrero and we think that it might be better to focus on testing functionality instead of system diversity (though it is important to have the diversity within, the organization of testing should be adapted for functionality). Perhaps take a series of systems as a standard set and try to run them through each posibility of the code (considering that some functionalities may require to expand the set, like openshell).

Also, what do you think about the scripts being in python? Do you handle the language? Do you think that in this case is more convenient than a bashscript? I know little of python but I can learn if it is worth it.

(2) I guess fosfato is from @nanolebrero ? Perhaps he can tell us what he thinks about the difference in energy depending on when was the "reference" ran? (example: if it was ran on rc before the latest fix)

 I only have one comment here: I don't understand why is there a hardcoded limit on the basis set (I'm talking about the fullereno problem); is there a reason or is it just old code we haven't changed yet?

**Comment by chopkins906** [comment] 2015-07-14 22:39
(1) I think this type of test system organization sounds ok, as long as you can still choose a subset of features to test (e.g. to be able to say - compile and run test set with only GPU code, kind of like with the current script's "filter_rx" flag)

I'm honestly not familiar with the automated test scripts at all, so it's hard for me to say much about the choice of python.  Things like parsing the output file and using regular expressions like in run_tests.py are probably easier in python, though not impossible in bash.  Then there's correr-profiles.py, which I really don't know much about.  It seems like it can do things like make plots, which would be easier to do in python.

A bash script could just as easily run a basic test suite with a simple pass/fail output; staying in python would allow a more extensible and complex test setup in the long run.

I'm somewhat familiar with the base python language, so I might be able to help if we want to stay with it.  As a sidenote, learning python is never a bad idea, though I prefer Perl myself ;)

(2) As far as I can tell, the basis set limits are just old code, maybe from a time when memory was being allocated statically?  Just about all of the memory allocation is dynamic now, so I don't think they serve much purpose anymore - they could be replaced with runtime-read values.

**Comment by ramirezfranciscof** [comment] 2015-07-15 13:32
(1) Do you think it would be easy to create similar testing scripts using perl?

(2) is this so @nanolebrero ? Then perhaps it should be one of the modifications for the next release (not the one we are about to do).

**Comment by chopkins906** [comment] 2015-07-15 20:01
(1) Sorry, my phrasing was weird - I think we should stick with python for the tests.  It could be done with perl, but python is probably a more popular choice, and it's easier to learn.

**Comment by williamagudelo82** [comment] 2015-07-15 20:11
(1) I prefer bash ( and little awk ;) ) !!!

**Comment by fedepedron** [comment] 2016-12-22 20:46
The issue is duplicated and will be fixed in the upcoming release.

**Closed by fedepedron** 2016-12-22 20:46 UTC
Labels: duplicate
